"""add_last_payment_reminder_to_rma

Revision ID: 261129ec9ab8
Revises: 81deeea96503
Create Date: 2025-10-14 18:04:29.996613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261129ec9ab8'
down_revision: Union[str, None] = '81deeea96503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rmas', sa.Column('last_payment_reminder', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rmas', 'last_payment_reminder')
    # ### end Alembic commands ###
