"""add_shipping_companies_table

Revision ID: 3cc9df7ffb9b
Revises: e39f2e2ef90f
Create Date: 2025-11-13 00:22:26.180776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc9df7ffb9b'
down_revision: Union[str, None] = 'e39f2e2ef90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_companies_id'), 'shipping_companies', ['id'], unique=False)
    op.create_index(op.f('ix_shipping_companies_name'), 'shipping_companies', ['name'], unique=True)
    op.create_table('shipping_company_countries',
    sa.Column('shipping_company_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipping_company_id'], ['shipping_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shipping_company_id', 'country_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping_company_countries')
    op.drop_index(op.f('ix_shipping_companies_name'), table_name='shipping_companies')
    op.drop_index(op.f('ix_shipping_companies_id'), table_name='shipping_companies')
    op.drop_table('shipping_companies')
    # ### end Alembic commands ###
