"""add_rma_attachments_table

Revision ID: 5615bd776411
Revises: 485bbeb13237
Create Date: 2025-10-14 15:56:36.092113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5615bd776411'
down_revision: Union[str, None] = '485bbeb13237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rma_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rma_id', sa.Integer(), nullable=False),
    sa.Column('attachment_type', sa.Enum('QUOTE', 'INVOICE', name='attachmenttype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('replaced_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by'], ['rma_attachments.id'], ),
    sa.ForeignKeyConstraint(['rma_id'], ['rmas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_rma_attachments_attachment_type'), 'rma_attachments', ['attachment_type'], unique=False)
    op.create_index(op.f('ix_rma_attachments_id'), 'rma_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_rma_attachments_is_latest'), 'rma_attachments', ['is_latest'], unique=False)
    op.create_index(op.f('ix_rma_attachments_rma_id'), 'rma_attachments', ['rma_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rma_attachments_rma_id'), table_name='rma_attachments')
    op.drop_index(op.f('ix_rma_attachments_is_latest'), table_name='rma_attachments')
    op.drop_index(op.f('ix_rma_attachments_id'), table_name='rma_attachments')
    op.drop_index(op.f('ix_rma_attachments_attachment_type'), table_name='rma_attachments')
    op.drop_table('rma_attachments')
    # ### end Alembic commands ###
