"""add_shipping_fields_to_rma

Revision ID: 81deeea96503
Revises: ac0ee90d51a6
Create Date: 2025-10-14 16:58:55.026697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81deeea96503'
down_revision: Union[str, None] = 'ac0ee90d51a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rmas', sa.Column('shipping_company', sa.String(length=255), nullable=True))
    op.add_column('rmas', sa.Column('tracking_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rmas', 'tracking_id')
    op.drop_column('rmas', 'shipping_company')
    # ### end Alembic commands ###
