"""update lenght code country

Revision ID: 83c459b8aaae
Revises: c8a1b7e22d3a
Create Date: 2025-12-03 21:47:12.293617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c459b8aaae'
down_revision: Union[str, None] = 'c8a1b7e22d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'code',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'code',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###
