"""add_description_to_brand

Revision ID: e39f2e2ef90f
Revises: 46c7ccb488ca
Create Date: 2025-11-11 12:40:05.010956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39f2e2ef90f'
down_revision: Union[str, None] = '46c7ccb488ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'description')
    # ### end Alembic commands ###
